# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/lab4bd/lab4bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4bd || ORIG_REF_NAME==lab4bd}]

# IP: bd/lab4bd/ip/lab4bd_processing_system7_0_0/lab4bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4bd_processing_system7_0_0 || ORIG_REF_NAME==lab4bd_processing_system7_0_0}]

# IP: bd/lab4bd/ip/lab4bd_multiply_0_0/lab4bd_multiply_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4bd_multiply_0_0 || ORIG_REF_NAME==lab4bd_multiply_0_0}]

# IP: bd/lab4bd/ip/lab4bd_processing_system7_0_axi_periph_0/lab4bd_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4bd_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==lab4bd_processing_system7_0_axi_periph_0}]

# IP: bd/lab4bd/ip/lab4bd_rst_processing_system7_0_100M_0/lab4bd_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4bd_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==lab4bd_rst_processing_system7_0_100M_0}]

# IP: bd/lab4bd/ip/lab4bd_auto_pc_0/lab4bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4bd_auto_pc_0 || ORIG_REF_NAME==lab4bd_auto_pc_0}]

# XDC: bd/lab4bd/ip/lab4bd_processing_system7_0_0/lab4bd_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab4bd_processing_system7_0_0 || ORIG_REF_NAME==lab4bd_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/lab4bd/ip/lab4bd_rst_processing_system7_0_100M_0/lab4bd_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4bd_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==lab4bd_rst_processing_system7_0_100M_0}]

# XDC: bd/lab4bd/ip/lab4bd_rst_processing_system7_0_100M_0/lab4bd_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4bd_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==lab4bd_rst_processing_system7_0_100M_0}]

# XDC: bd/lab4bd/ip/lab4bd_rst_processing_system7_0_100M_0/lab4bd_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/lab4bd/ip/lab4bd_auto_pc_0/lab4bd_auto_pc_0_ooc.xdc

# XDC: bd/lab4bd/lab4bd_ooc.xdc
