# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq/zynq.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq || ORIG_REF_NAME==zynq}]

# IP: bd/zynq/ip/zynq_processing_system7_0_0/zynq_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_processing_system7_0_0 || ORIG_REF_NAME==zynq_processing_system7_0_0}]

# IP: bd/zynq/ip/zynq_multiply_0_0/zynq_multiply_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_multiply_0_0 || ORIG_REF_NAME==zynq_multiply_0_0}]

# IP: bd/zynq/ip/zynq_processing_system7_0_axi_periph_0/zynq_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==zynq_processing_system7_0_axi_periph_0}]

# IP: bd/zynq/ip/zynq_rst_processing_system7_0_100M_0/zynq_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==zynq_rst_processing_system7_0_100M_0}]

# IP: bd/zynq/ip/zynq_auto_pc_0/zynq_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_auto_pc_0 || ORIG_REF_NAME==zynq_auto_pc_0}]

# XDC: bd/zynq/ip/zynq_processing_system7_0_0/zynq_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_processing_system7_0_0 || ORIG_REF_NAME==zynq_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/zynq/ip/zynq_rst_processing_system7_0_100M_0/zynq_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==zynq_rst_processing_system7_0_100M_0}]

# XDC: bd/zynq/ip/zynq_rst_processing_system7_0_100M_0/zynq_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==zynq_rst_processing_system7_0_100M_0}]

# XDC: bd/zynq/ip/zynq_rst_processing_system7_0_100M_0/zynq_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/zynq/ip/zynq_auto_pc_0/zynq_auto_pc_0_ooc.xdc

# XDC: bd/zynq/zynq_ooc.xdc
