# 
# Synthesis run script generated by Vivado
# 

set_param project.hsv.suppressChildGraphs 0
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/clvrpny/ecen449/lab04/lab04.cache/wt [current_project]
set_property parent.project_path /home/clvrpny/ecen449/lab04/lab04.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.0 [current_project]
set_property ip_repo_paths /home/clvrpny/ecen449/ip_repo [current_project]
add_files /home/clvrpny/ecen449/lab04/lab04.srcs/sources_1/bd/lab4bd/lab4bd.bd
set_property used_in_implementation false [get_files -all /home/clvrpny/ecen449/lab04/lab04.srcs/sources_1/bd/lab4bd/ip/lab4bd_processing_system7_0_0/lab4bd_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/clvrpny/ecen449/lab04/lab04.srcs/sources_1/bd/lab4bd/ip/lab4bd_rst_processing_system7_0_100M_0/lab4bd_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/clvrpny/ecen449/lab04/lab04.srcs/sources_1/bd/lab4bd/ip/lab4bd_rst_processing_system7_0_100M_0/lab4bd_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/clvrpny/ecen449/lab04/lab04.srcs/sources_1/bd/lab4bd/ip/lab4bd_rst_processing_system7_0_100M_0/lab4bd_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/clvrpny/ecen449/lab04/lab04.srcs/sources_1/bd/lab4bd/ip/lab4bd_auto_pc_0/lab4bd_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/clvrpny/ecen449/lab04/lab04.srcs/sources_1/bd/lab4bd/lab4bd_ooc.xdc]
set_property is_locked true [get_files /home/clvrpny/ecen449/lab04/lab04.srcs/sources_1/bd/lab4bd/lab4bd.bd]

read_verilog -library xil_defaultlib /home/clvrpny/ecen449/lab04/lab04.srcs/sources_1/bd/lab4bd/hdl/lab4bd_wrapper.v
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top lab4bd_wrapper -part xc7z010clg400-1
write_checkpoint -noxdef lab4bd_wrapper.dcp
catch { report_utilization -file lab4bd_wrapper_utilization_synth.rpt -pb lab4bd_wrapper_utilization_synth.pb }
