webtalk_init -webtalk_dir /home/clvrpny/ecen449/lab02/lab02.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Feb 3 19:32:33 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1k91oimc3qu917i069iik91usb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.2_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1580749697000" -context "sdk\\\\bsp/1580749697000"
webtalk_add_data -client sdk -key hwid -value "1580269618000" -context "sdk\\\\bsp/1580749697000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1580749697000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1580749697000"
webtalk_add_data -client sdk -key uid -value "1580749697000" -context "sdk\\\\application/1580749697000"
webtalk_add_data -client sdk -key hwid -value "1580269618000" -context "sdk\\\\application/1580749697000"
webtalk_add_data -client sdk -key bspid -value "1580749697000" -context "sdk\\\\application/1580749697000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1580749697000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1580749697000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1580749697000"
webtalk_transmit -clientid 1313154178 -regid "" -xml /home/clvrpny/ecen449/lab02/lab02.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/clvrpny/ecen449/lab02/lab02.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/clvrpny/ecen449/lab02/lab02.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
