obj-m += hello.o

all:
	make -C /home/ugrads/p/philipsmith/new/ecen449/lab05/local_kern/linux-3.14 M=$(PWD)	modules

clean:
	make -C /home/ugrads/p/philipsmith/new/ecen449/lab05/local_kern/linux-3.14 M=$(PWD)	clean
