set_property SRC_FILE_INFO {cfile:/home/clvrpny/ecen449/lab02/lab02.srcs/sources_1/bd/led_sw/ip/led_sw_clk_wiz_1_0/led_sw_clk_wiz_1_0.xdc rfile:../../../lab02.srcs/sources_1/bd/led_sw/ip/led_sw_clk_wiz_1_0/led_sw_clk_wiz_1_0.xdc id:1 order:EARLY scoped_inst:led_sw_i/clk_wiz_1/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/clvrpny/ecen449/lab02/lab02.srcs/constrs_1/new/led.xdc rfile:../../../lab02.srcs/constrs_1/new/led.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.1
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_clock −add −name sys_clk_pin −period 10.00 −waveform {0 5} [ get_ports clock_rtl ]
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set property PACKAGE_PIN G15 [ get_ports { buttons_tri_i[0]}]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set property IOSTANDARD LVCMOS33 [ get_ports { buttons_tri_i[0]}]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set property PACKAGE_PIN P15 [ get_ports { buttons_tri_i[1]}]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set property IOSTANDARD LVCMOS33 [ get_ports { buttons_tri_i[1]}]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set property PACKAGE_PIN W13 [ get_ports { buttons_tri_i[2]}]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set property IOSTANDARD LVCMOS33 [ get_ports { buttons_tri_i[2]}]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set property PACKAGE_PIN T16 [ get_ports { buttons_tri_i[3]}]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set property IOSTANDARD LVCMOS33 [ get_ports { buttons_tri_i[3]}]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set property PACKAGE_PIN R18 [ get_ports { buttons_tri_i[4]}]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set property IOSTANDARD LVCMOS33 [ get_ports { buttons_tri_i[4]}]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set property PACKAGE_PIN P16 [ get_ports { buttons_tri_i[5]}]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set property IOSTANDARD LVCMOS33 [ get_ports { buttons_tri_i[5]}]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set property PACKAGE_PIN V16 [ get_ports { buttons_tri_i[6]}]
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set property IOSTANDARD LVCMOS33 [ get_ports { buttons_tri_i[6]}]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set property PACKAGE_PIN Y16 [ get_ports { buttons_tri_i[7]}]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set property IOSTANDARD LVCMOS33 [ get_ports { buttons_tri_i[7]}]
