set property PACKAGE PIN K17 [ get_ports clock_rtl ]
set property IOSTANDARD LVCMOS33 [ get_ports clock_rtl ]
create clock −add −name sys_clk_pin −period 10.00 −waveform {0 5} [ get_ports clock_rtl ]
set property PACKAGE PIN M14 [ get_ports { led_tri_o[0]}]
set property IOSTANDARD LVCMOS33 [ get_ports { led_tri_o[0]}]
set property PACKAGE PIN M15 [ get_ports { led_tri_o[1]}]
set property IOSTANDARD LVCMOS33 [ get_ports { led_tri_o[1]}]
set property PACKAGE PIN G14 [ get_ports { led_tri_o[2]}]
set property IOSTANDARD LVCMOS33 [ get_ports { led_tri_o[2]}]
set property PACKAGE PIN D18 [ get_ports { led_tri_o[3]}]
set property IOSTANDARD LVCMOS33 [ get_ports { led_tri_o[3]}]
